Misc bugs 4
modrinth/theseus pull request #381
Opened 2023-07-28 01:18 UTC by thesuzerain

Fixes #369 #175 #373 #225 #316 #369 #285 #197 #345 #210

(#225 also requires omorphia pr)

2023-07-28 03:21 UTC, SpiralshapeOfficial commented
#369 is mentioned twice

2023-07-28 03:23 UTC, Fnige commented
Yeah suze double fixed it

2023-07-28 19:51 UTC, Geometrically requested changes

2023-07-28 19:51 UTC, Geometrically commented on theseus_gui/src/pages/instance/Options.vue
> +  />
don't think these are needed. they aren't destructive actions

2023-07-29 02:54 UTC, Geometrically approved these changes

2023-07-29 02:56 UTC, merged