Finishes wiring up the profile page.
modrinth/theseus pull request #93
Opened 2023-04-21 02:47 UTC by ZachBaird

Fixes MOD-373

- Play button and stop button are wired to the correct events
- A loading button has been added per task requirement

2023-04-21 02:49 UTC, ZachBaird commented
Note that this branch will suffer from the same deadlock and kill_process problems that wire-up-homepage does.

2023-04-21 22:59 UTC, Geometrically requested changes
this should integrate with the process events API (also use `get_uuids_by_profile_path` to make sure it's synced up to everything else)

2023-04-27 01:25 UTC, ZachBaird commented
For some reason, getting uuids by profile path just hangs for me. So if you:

1. Navigate away from the instance page
2. Navigate back to it
3. Click the Stop btn

It won't work. It doesn't even return the list of uuids.

2023-05-06 00:43 UTC, Geometrically requested changes
There's also another bug with the navbar not updating when processes are killed from somewhere else. could you fix that in this PR?

2023-05-06 00:43 UTC, Geometrically commented on theseus_gui/src/pages/instance/Index.vue
> +})
Won't this not work if you have multiple instances running? it should check the PID to make sure it's the right one

2023-05-10 00:26 UTC, Geometrically approved these changes

2023-05-10 00:26 UTC, merged